### ISSUE TITLE
parameter 'mappings' expects an Array value, got Struct

### ISSUE THREAD

**Issue by jurim76** [voxpupuli/puppet-autofs#125]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.10.4
- Ruby: 2.3.3 
- Distribution: Debian 9
- Module version: 5.0.0

## How to reproduce (e.g Puppet code you use)
hiera yaml example

autofs::mounts:
  gmail:
    mount:    '/srv'
    mapfile:  '/etc/auto.master.d/auto.gmail'
#
autofs::mapfiles:
  gmail:
    path: '/etc/auto.master.d/auto.gmail'
    mappings:
      key: 'gmail'
      options: 'rw,soft,intr,tcp,nfsvers=4,noacl'
      fs: 'ld-sys-smb:/srv/gmail'

## What are you seeing
> puppet agent -t
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Autofs::Mapfile[gmail]: parameter 'mappings' expects an Array value, got Struct at /srv/puppet/env/production/modules/autofs/manifests/init.pp:111

**Comment by sycobuny** [comment]
This seems likely to be a bug in documentation rather than code. The [README](https://github.com/voxpupuli/puppet-autofs/blob/v5.0.0/README.md#map-files) shows the following YAML snippet as an example (which matches the style of the input above):

```yaml
autofs::mapfiles:
  home:
    path: '/etc/auto.home'
    mappings:
      key: '*'
      options: 'rw,soft,intr'
      fs: 'server.example.com:/path/to/home/shares'
```

Whereas, [per the definition of Autofs::Mapfile](https://github.com/voxpupuli/puppet-autofs/blob/v5.0.0/manifests/mapfile.pp#L23) (and the error message the user listed above), you probably want a snippet that looks more like the following, which ensures that the `mappings` element is parsed as an Array rather than a Struct:

```yaml
autofs::mapfiles:
  home:
    path: '/etc/auto.home'
    mappings:
      - key: '*'
        options: 'rw,soft,intr'
        fs: 'server.example.com:/path/to/home/shares'
```

I can certainly fork and submit a pull request, but for a minor change like this it may be faster for someone on the team to update the repo directly.

In any case, the YAML which I believe *should* work for @jurim76 would look like this instead:

```yaml
autofs::mapfiles:
  gmail:
    path: '/etc/auto.master.d/auto.gmail'
    mappings:
      - key: 'gmail'
        options: 'rw,soft,intr,tcp,nfsvers=4,noacl'
        fs: 'ld-sys-smb:/srv/gmail'
```
