### ISSUE TITLE
autofs mount 

### ISSUE THREAD

**Issue by emerald010** [voxpupuli/puppet-autofs#92]
What am I doing wrong here?

#autofs
autofs::mounts:
'home':
mountpoint: '/mnt/nov'
remote: '10.x.x.x:/nov'
options: '-rw,intr,timeo=20'

This is configured in a node yaml file for that particular node. The puppet run recognizes the change but it does not implement it. Previously configured node has similar settings except the mount point and the remote server ip is different. If I run 'mount' command directly on the server, it works.
Puppet 2016.4.3

**Comment by dhollinger** [comment]
Sorry for the delay. I'll take a look at it this weekend.

Do you have any additional information about your setup that could help?

What version of Hiera - 3, 4, or 5?
Is the issue only seen on one node, multiple nodes, or all nodes?
Is the `home` mount defined in any other hieradata file?
What about Puppet run and/or system logs?

**Comment by dhollinger** [comment]
@emerald010 I think I found the issue in your hieradata. There is no `remote` parameter in this module.

Here is your yaml:
``` yaml
#autofs
autofs::mounts:
  'home':
    mountpoint: '/mnt/nov'
    remote: '10.x.x.x:/nov'
    options: '-rw,intr,timeo=20'
```

Here is what it has to look like to work:
``` yaml
#autofs
autofs::mounts:
  'home':
    mount: '/mnt/nov'
    mapcontents: ['10.x.x.x:/nov']
    options: '-rw,intr,timeo=20'
```

This will also work:
``` yaml
#autofs
autofs::mounts:
  'home':
    mount: '/mnt/nov'
    mapcontents: ['10.x.x.x:/nov -rw,intr,timeo=20']
```
